name: E2E
on: push
jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run with env
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_host: 0.0.0.0
          CYPRESS_port: 3001
