name: E2E
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          config-file: e2e/cypress.json
          start: npm run test:e2e
          wait-on: "http://0.0.0.0:3001"
        env:
          DEV_SERVER_PORT: 3001