name: E2E
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config-file: test/e2e/cypress.json
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3001'
          wait-on-timeout: 120
